### ISSUE TITLE
import oommfc as oc ERROR

### ISSUE THREAD

**Issue by zkhodzhaev** [joommf/help#1]
The error is attached:
<img width="901" alt="Screen Shot 2019-08-21 at 23 30 58" src="https://user-images.githubusercontent.com/21960382/63486226-3834b080-c46c-11e9-9b81-7b7a7ebc2b3e.png">

**Comment by marijanbeg** [comment]
Hi @Zulfidin, the project has been renamed to Ubermag. Therefore, all the support questions should be posted in https://github.com/ubermag/help.

I addressed this question in https://github.com/ubermag/oommfc/issues/45, so I will close it here.

Thank you again for using Ubermag :)
