### ISSUE TITLE
JOOMMFC installation

### ISSUE THREAD

**Issue by owliktuk** [joommf/help#1]
Hello,
I try to install OOMMFC following instructions at http://oommfc.readthedocs.io/en/latest/ipynb/installation.html. My system is Linux OpenSuse 13.2.
Installation fails at the last step : python3 -m pip install oommfc
I am attaching output from terminal
Thanks for helpin advance
[oommf_term.txt](https://github.com/joommf/help/files/946828/oommf_term.txt)

**Comment by mb1a15** [comment]
Hi,
Unfortunately, we do not support OpenSuse Linux distribution. By looking at your output, it seems you are  having problems installing `numpy` (http://www.numpy.org/) which is one of JOOMMF's dependencies. You could maybe try installing numpy through the OpenSUSE package manager which may fix this problem, before trying to install 'oommfc' again.

We don't have an OpenSUSE machine to test our software on, so we suggest that if this doesn't work that you could try using the Anaconda python distribution - this installs a parallel version of Python on your operating system, with the aim to better support different types of operating system.

**Comment by owliktuk** [comment]
Thank you very much, installing python3-numpy helped.
