### ISSUE TITLE
mumax3c 

### ISSUE THREAD

**Issue by mickduns** [joommf/help#10]
Hello, and thank you for a great introductory workshop session! I was wondering if you could tell me how I can begin working with mumax3c immediately rather than having to wait for the final lecture? In my research we do not use OOMMF, instead we exclusively use mumax3, but already I am seeing tremendous potential for my own work using Ubermag's Jupyter interface. I would like to start replicating and expanding on your introductory notebook code on my own however I cannot import the mumax3c package. Any help with this situation is greatly appreciated.

**Comment by marijanbeg** [comment]
This issue is being addressed here: https://github.com/ubermag/help/issues/62
