### ISSUE TITLE
OOMFC test failed

### ISSUE THREAD

**Issue by kannanum** [joommf/help#10]
Dear JOOMMF team,
                                        I am a new user to joommf. My system and software configuration are as follows:
OS : windows7 professional, 32 bit
Tcl version: 8.5.18.0
OOMMF version: OOMMF 1.2 beta 0 (30-Sep-2016). (Source with pre-compiled 32-bit Windows - 
                            executables (x86) for 32-bit Tcl/Tk 8.5.x)
After installing oommfc as per the installation instructions (without docker), when i try to run the test using python -c "import oommfc; oommfc.test()", i get the message 14 failed and 112 passed. please see attached screenshot of anaconda prompt. 
![oommfc error test](https://user-images.githubusercontent.com/31684180/30097255-6177b58c-92fa-11e7-85a8-75fc5ddf4520.PNG)
I have also tried to run the first_oommfc_notebook via jupyter where i am getting the following error messages:
![error1](https://user-images.githubusercontent.com/31684180/30097336-cdfe9db0-92fa-11e7-889e-75e17c943b28.PNG)
![error2](https://user-images.githubusercontent.com/31684180/30097341-d2428814-92fa-11e7-9243-913a73c090a0.PNG)
appologies for the long query. but please help me with this problem

**Comment by rpep** [comment]
Hi Kannanum,

It looks to me like for some reason it can't access the executable even though it's there, (which is why you get the permission denied message). Could you try launching 'cmd' with administrator priveleges? (if you don't know how to do this, just search for 'cmd' in the Start menu, then right click it and then click 'Run as an administrator').

I'm not sure what's happened here, as you don't need admin rights to run Joommf generally. I'll try and see if I can replicate your error on my own Windows 10 computer.

Best wishes,
Ryan

**Comment by kannanum** [comment]
Dear Ryan,
                      Thanks for the reply. I have tried starting the anaconda prompt as admin. I tried uninstalling oommfc ( pip uninstall oommfc)  and reinstalling. But still the test gives the same error message as before.
i tried the following tests as well:
a)python -c "import oommfc; oommfc.test_not_oommf()"

![error3](https://user-images.githubusercontent.com/31684180/30099465-6441d9a6-9303-11e7-8d89-2d72e4b30c91.PNG)

b)import oommfc
oommfc.oommf.status()

![error4](https://user-images.githubusercontent.com/31684180/30099552-ac2bd1ea-9303-11e7-8fce-14df429a02a7.PNG)

c)oommfc.oommf.version(where="host")
attribute error: module 'oommfc.oommf' has no attribute 'version'

d)python -c "import oommfc; oommfc.test_oommf()"

![error5](https://user-images.githubusercontent.com/31684180/30099746-473261b8-9304-11e7-8475-650490c64976.PNG)

**Comment by kannanum** [comment]
Dear Ryan,
                         The issue got resolved. It was a case of my antivirus program blocking the execution of omfsh.exe. Thanks for the help

**Comment by rpep** [comment]
Ah great! Thank you for letting us know what the problem was!
