### ISSUE TITLE
Oommf taking too long to perform calculations

### ISSUE THREAD

**Issue by AkravasTheWise** [joommf/help#12]
Hi,

For some reason, my Oommf takes up to five times more time to perform simple calculations in contrast with examples I've found online. I am running previously installed Oommf with Tcl. Here is an example of the output:

Running OOMMF (TclOOMMFRunner) [2020/08/24 11:23]... (9.8 s)

This code should take no more than 2 seconds.

Thanks in advance

**Comment by marijanbeg** [comment]
This question is addressed in official help repository.
