### ISSUE TITLE
Fixing magnetisation in a given region 

### ISSUE THREAD

**Issue by askeyjw** [joommf/help#13]
Hello, I am pretty new to Ubermag but have used MuMax3 in my other research. I was wondering if there is a way to essentially fix the magnetisation in a particular region such that they do not evolve when I minimise the system? For example, if I have a square wire and I wanted to fix the two ends of the wire, randomise the centre of the wire, then relax the system so that a domain wall is forced to form in the wire. There is a function that can do this in MuMax3 called "FrozenSpins" but I have not been able to figure out how to do this same process in Ubermag (if it is even possible!). Thank you for taking the time to read my question/issue, and I'm really enjoying using Ubermag!

**Comment by marijanbeg** [comment]
This issue is addressed here: https://github.com/ubermag/help/issues/84

Please note that we provide Ubermag support in this repository: https://github.com/ubermag/help
