### ISSUE TITLE
regarding to problems that show during OOMMFC's installation

### ISSUE THREAD

**Issue by soysaucesalesman** [joommf/help#15]
Dear members, 
I am very new to OOMMF and OOMMFC,
I have attached few pictures showing the problem, I don'
![error](https://user-images.githubusercontent.com/34221889/33531932-339bebfe-d8cf-11e7-9fda-dfbd8c44b427.PNG)
![problem that shows in a simple simulation](https://user-images.githubusercontent.com/34221889/33531933-33c27f30-d8cf-11e7-8d42-18cd960ec31c.PNG)
![process stopped during testing for oommf and oommfc](https://user-images.githubusercontent.com/34221889/33531934-33e8855e-d8cf-11e7-81cd-9fc13ab906e2.PNG)

t even know how to describe them.
can anyone explain to me what's going on?
thanks.

**Comment by marijanbeg** [comment]
Hi,

Can you give us more information about the system you use. We can see that you use Windows, but do you have administrator rights or you are a user. In addition, can you run the following lines in your Command Prompt and report the results you get to us:

`python3 -c "import oommfc; oommfc.test_not_oommf()"`
`python3 -c "import oommfc; oommfc.test_oommf()"`

**Comment by soysaucesalesman** [comment]
Hello,
My system is windows 7, 64bit version.
Also ,I am the administrator.
since my system is windows, I follow the construction by running the lines:

python -c "import oommfc; oommfc.test_not_oommf()"      

I have attached the results. please have a look. thank  you.
![administrator](https://user-images.githubusercontent.com/34221889/33792156-7f07be58-dcd3-11e7-8879-be90e252d2ac.JPG)
![default](https://user-images.githubusercontent.com/34221889/33792161-8eab9a32-dcd3-11e7-9982-ba0788fd87d5.JPG)
![1](https://user-images.githubusercontent.com/34221889/33792167-9419edd4-dcd3-11e7-9898-973381bdee14.JPG)
![2](https://user-images.githubusercontent.com/34221889/33792168-9839f724-dcd3-11e7-87aa-cadb00bd08e4.JPG)
![3](https://user-images.githubusercontent.com/34221889/33792169-9c2a647c-dcd3-11e7-8a38-f9b0622cfc73.JPG)

when I run: python -c "import oommfc; oommfc.test_oommf()", the result is:
![4](https://user-images.githubusercontent.com/34221889/33792183-12e1ce84-dcd4-11e7-8d46-66b785d06322.JPG)
![5](https://user-images.githubusercontent.com/34221889/33792185-168a82ce-dcd4-11e7-8373-3fe1d57e08b0.JPG)

Thank you very much for comment.

**Comment by rpep** [comment]
When you run 'Command Prompt' from Program Files, can you try right clicking it instead and clicking 'Run as Administrator'?

**Comment by soysaucesalesman** [comment]
I actually did.

**Comment by marijanbeg** [comment]
Hi, when you run tests, could you please wait for them to complete (it may take about 5 min). When they are done, you should get a short report on how many tests passed/failed.

**Comment by marijanbeg** [comment]
Hi @soysaucesalesman , we managed to hopefully simplify installation of JOOMMF on all platforms - including Windows. To install JOOMMF, after you install Anaconda Python distribution, running:
```
conda install --channel conda-forge oommfc
```
in your terminal/command prompt should be sufficient. Could you please let us know if this does not work for you?

**Comment by marijanbeg** [comment]
I would assume this issue is now resolved. If not, @soysaucesalesman, feel free to reopen it.
