### ISSUE TITLE
snapshots of vortex formation in a disc

### ISSUE THREAD

**Issue by physics2357** [joommf/help#16]
Hello,
 I am studying the for formation of magnetic  vortices in a  disc using ubermag. I could obtain the hysteris loop . But I am not able to visualise the magnetization configuration at each field using ubermag. How can I do it ? I s there any option for taking the snapshots at each field using ubermag?
Thank you.

**Comment by marijanbeg** [comment]
Hi @physics2357, please have a look at the second part of this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/hysteresis.ipynb

I hope this helps.

**Comment by physics2357** [comment]
hi @marijanbeg ,
Thank you so much. it is working perfectly. I have one more doubt. How could I find the field at which the vortex occurs? its really hard to find from the odt file.
thank you
