### ISSUE TITLE
Technique errors appeared

### ISSUE THREAD

**Issue by lamducduong184** [joommf/help#16]
Dear developer teams,

I came back to do JOOMMF simulation after few months.
But there is some new errors when I use these lines:

1. system.m.plot_slice('x', 50e-9)
2. EF = system.hamiltonian.effective_field
----------------------------------------
OOMMFTCL is set, but there was a problem running oommf.
stdout:
Capture-1

stderr:
Capture-2
Error running docker
stdout:
Capture-3

stderr:
Capture-4
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-16-683c99a36a84> in <module>()
----> 1 EF = system.hamiltonian.effective_field
...

Do I need to install again or update something?

Thank you for your helps!

Best regards,
Lam Duc Duong

**Comment by marijanbeg** [comment]
Hi, it seems there is a problem with your installation. What operating system are you using? Can you install JOOMMF again?

**Comment by lamducduong184** [comment]
Thank you Marijan,
This is Window 10 OS on Desktop machine. I did try install again many times but no luck.
On Macbook laptop, it works well.

**Comment by marijanbeg** [comment]
Hi @lamducduong184, we managed to hopefully simplify installation of JOOMMF on all platforms - including Windows. To install JOOMMF, after you install Anaconda Python distribution, running:

```
conda install --channel conda-forge oommfc
```

in your terminal/command prompt should be sufficient. Could you please let us know if this does not work for you?

**Comment by lamducduong184** [comment]
Hi Marijan,

Thank you so much,
I did and I can run the .ipynb file on Jupyter notebook. 
But the program never pass the MinDrive step:

md = oc.MinDriver()
md.drive(system)
2018/7/26 10:34: Calling OOMMF (conversion5\conversion5.mif) ... 

But I still can run it on my Macbook!

**Comment by marijanbeg** [comment]
Hi @lamducduong184, can you please follow the installation instructions from one of the videos from this page:

https://oommfc.readthedocs.io/en/latest/ipynb/installation.html

Please let us know if it still does not work.

**Comment by lamducduong184** [comment]
Dear Marijan,

Thank you so much for your kind support.
I am super busy recently, so I cound not reply you soon.

Best regards,
Lam Duc Duong

Vào Th 3, 11 thg 9, 2018 vào lúc 21:16 Marijan Beg <
notifications@github.com> đã viết:

**Comment by marijanbeg** [comment]
I will now consider that this issue has been resolved.

Please let us know if you have any further questions and feel free to reopen this issue if I did not answer your question.
