### ISSUE TITLE
Problems regarding the installation

### ISSUE THREAD

**Issue by jaroal95** [joommf/help#18]
Hi,

I own a 64 bit Ubuntu 16.04 LTS

I'm pretty new to oommf and python, but I have followed the instructions step by step and still i i am not able pass the tests. 

When I enter the line " python3 -c "import oommfc; oommfc.test()" " on the command prompt I get the following answer:
![error oommfc](https://user-images.githubusercontent.com/38592103/39088030-862bf528-45ab-11e8-9e95-82d1d25feb25.png)
Also, additional warnings and error messages raise when I try to run my python programmes, always referring to the fact that it haven't been possible to find the DOCKER.

I would appreciate any advice

**Comment by fangohr** [comment]
Have you tried to install docker (http://docker.com) yet?

Without having tried this recently, after a quick google search this seems like the procedure to follow: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04, or - directly from docker: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by fangohr** [comment]
Thanks for the feedback.
