### ISSUE TITLE
problem regarding installation extension file of DMI in oommf

### ISSUE THREAD

**Issue by kushalphy** [joommf/help#2]
i am facing problem when reinstalling the oommf for the dmi extension files.i have followed all the instructions as given.a text file regarding this problem is attached with this.it is a command prompt window instruction.
thank you 
[New Text Document.txt](https://github.com/joommf/help/files/3742578/New.Text.Document.txt)

**Comment by marijanbeg** [comment]
Hi @kushalphy, thank you for you question. DMI extensions are unfortunately no available on Windows, only Linux and MacOS.

**Comment by kushalphy** [comment]
thanks for the information @marijanbeg

**Comment by Harry-09** [comment]
Does DMI_Cnv class extensions for OOMMF are supported by windows ?If so please guide me for installing it, as I'm getting errors  
![Capture](https://user-images.githubusercontent.com/59189839/104200070-38ad5d00-544e-11eb-8fe6-66094bb29c26.PNG)
 while installing the extension.

Thanks in Advance !!!
