### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by fangohr** [joommf/help#21]
The nice anaconda based installation (as described at 
https://github.com/joommf/icm2018-workshop), should feature in the main documentation, and replace (or at least be shown first) the existing manual installation of OOMMF instructions.

**Comment by marijanbeg** [comment]
The installation instructions have been updated to describe Conda installation and also give links to YouTube videos (https://oommfc.readthedocs.io/en/latest/ipynb/installation.html).

**Comment by fangohr** [comment]
Thank you - nice!

Two more queries: is it possible to put the whole end of the section (starting from https://oommfc.readthedocs.io/en/latest/ipynb/installation.html#Advanced) into a separate file, so that the casual reader only sees the anaconda instructions? I worry that people think the installation is very complicated because the page is so long.

Related: at the end of the anaconda install instructions, it would be good to have a "test your installation" section, with either a link to how to run the tests, or a short example to to run the tests.

**Comment by marijanbeg** [comment]
This is now separated and extended.
