### ISSUE TITLE
Stray field

### ISSUE THREAD

**Issue by talekarpm1** [joommf/help#23]
How to calculate stray field 100nm above the permalloy sample surface

**Comment by marijanbeg** [comment]
This is now answered in issue #24. After you compute the stray field, you can ask for its value as `stray_field(point)`, where `point` is an (x, y, z) tuple defining where you want to sample the stray field.

Please let us know if you have any further questions and feel free to reopen this issue if I did not answer your question.

**Comment by talekarpm1** [comment]
Thanks a lot, but this was resolved already.

**Comment by talekarpm1** [comment]
Dear JOOMMF and Joommf/Help,
how to restart the program with restart file in oommfc

Thanks and Regards
Pranali

**Comment by marijanbeg** [comment]
Hi, what do you exactly mean? Could you give us more details? Thanks.

**Comment by talekarpm1** [comment]
I mean as in oommf we use .restart file to restart the stopped program. How
to do that in joommf

**Comment by marijanbeg** [comment]
Thank you for your explanation. Unfortunately, we do not support this feature in JOOMMF.

**Comment by talekarpm1** [comment]
Ok
Thanks and Regards
Pranali

**Comment by talekarpm1** [comment]
I want to simulate permalloy pattern of thickness 90nm. I am using
multiatlas for 0 to 90 nm permalloy than over that 90nm to 200nm it is air.
I want to give different cell size for both. How should I give that.

Thanks and Regards
Pranali
VNIT

**Comment by marijanbeg** [comment]
Hi @talekarpm1, in (most) finite difference codes (such as OOMMF), it is not allowed to use multiple cell sizes in simulations. This is a specific advantage of finite element codes. I understand this would decrease your simulation time and memory requirements, but unfortunately, this cannot be done.

**Comment by talekarpm1** [comment]
Thank u Marijan for a quick response. I have query about how to get MFM
images using joommf.

**Comment by marijanbeg** [comment]
You are welcome @talekarpm1. MFM images are not directly a part of JOOMMF, but you can use the following tool to convert the OOMMF ovf file to MFM images: http://www.southampton.ac.uk/~fangohr/software/ovf2mfm/
