### ISSUE TITLE
 create air box and inside that permalloy box

### ISSUE THREAD

**Issue by talekarpm1** [joommf/help#24]
how to create air box and inside that permalloy box. In oommf it is done using multiatlas

**Comment by marijanbeg** [comment]
Hi @talekarpm1,

Thank you for your question. This is done by defining a Python function for magnetisation field norm. Please have a look at the tutorial for stray field: https://github.com/joommf/oommfc/blob/master/docs/ipynb/stray-field.ipynb

Please let us know if you have any further questions and feel free to reopen this issue if I did not answer your question.

**Comment by fangohr** [comment]
Very nice.

**Comment by talekarpm1** [comment]
Thanks a lot

**Comment by himadri2024** [comment]
Dear all,

I have done the stray field simulation for a permalloy nanowire and plotted stray fields at different z heights. I have attached the file here.
[Demag_energy_Py.zip](https://github.com/ubermag/help/files/6917034/Demag_energy_Py.zip)

I am a little confused about the unit of the stray field in the y-axis. It is in 'Oe', 'mT' or something else.

Please help me in clarifying my doubt.

Thank you.
Regards,
Himadri

**Comment by marijanbeg** [comment]
Hi @himadri2024, thank you for your question. All fields are in A/m units.
