### ISSUE TITLE
how to give random field orientation in joommf system.m = df.Field(mesh, value=(random), norm=8e5)

### ISSUE THREAD

**Issue by talekarpm1** [joommf/help#28]
how to give random field orientation in joommf system.m = df.Field(mesh, value=(random), norm=8e5)

**Comment by marijanbeg** [comment]
Hi @talekarpm1,

Thank you for your question. You can define a function which returns a random vector and pass it to the Field class. For instance:

```
import random
import oommfc as oc
import discretisedfield as df

def my_random_field(pos):
    return [2*random.random()-1 for i in range(3)]

mesh = oc.Mesh(p1=(0, 0, 0), p2=(10, 10, 10), cell=(1, 1, 1))
field = df.Field(mesh, value=my_random_field, norm=8e5)
```

Please let us know if you have any further questions and feel free to reopen this issue if I did not answer your question.
