### ISSUE TITLE
JOOMMF testing

### ISSUE THREAD

**Issue by owliktuk** [joommf/help#3]
Hi, 
I installed JOOMMF on the newest Ubuntu system with your instructions. However, from ` python3 -c "import oommfc; oommfc.test()" ` command I get:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/owliktuk/.local/lib/python3.5/site-packages/oommfc/__init__.py", line 19, in test
    import pytest  # pragma: no cover
ImportError: No module named 'pytest'`

**Comment by mb1a15** [comment]
Hi,
If you want to run tests, you need to install `pytest`. You can install it by running:
```
python3 -m pip install pytest
```
in your terminal. After you install `pytest`, you can again try to run tests with: 
```
python3 -c "import oommfc; oommfc.test()"
```

Let us know if you have any other issues.

**Comment by mb1a15** [comment]
Documentation about testing is now updated to emphasise the installation of `pytest` before running tests.

**Comment by KingfaLuis** [comment]
import unittest
import pytest

class TestStringMethods(unittest.TestCase):

    def test_upper(self):
        self.assertEqual('foo'.upper(),'FOO')

    def test_isupper(self):
        self.assertTrue('FOO'.isupper())
        self.assertFalse('FOO'.isupper())

    def test_split(self):
        s = 'hello world'
        self.assertEqual(s.split(),['hello','world'])
        with self.assertRaises(TypeError):
            s.split(2)

if __name__ == '__main__':
    unittest.main()



get the Error
Traceback (most recent call last):
  File "G:\Program Files\JetBrains\PyCharm 2018.2.1\helpers\pycharm\_jb_pytest_runner.py", line 5, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'

**Comment by marijanbeg** [comment]
Can you tell us how you installed joommf? Did you install it using `conda` or `pip`?
