### ISSUE TITLE
windows 8 installation problem 

### ISSUE THREAD

**Issue by talekarpm1** [joommf/help#33]
(base) C:\Users\Hp>conda install --channel conda-forge joommf
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37hb782905_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37hdce8814_0
  - anaconda==2018.12=py37_0 -> scikit-learn==0.20.1=py37h343c172_0
  - joommf
Use "conda info <package>" to see the dependencies for each package.
I have tried installing as that in video

**Comment by talekarpm1** [comment]
I have tried installing as that in video

**Comment by Ponsudana** [comment]
Hi @talekarpm1,
Hope these links will help you,

https://stackoverflow.com/questions/48589141/anaconda-unsatisfiableerror-the-following-specifications-were-found-to-be-in

https://stackoverflow.com/questions/54205571/installing-tensorflow-using-anaconda-navigator-gives-unsatisfiableerror-for-pyth

Similarly, you can try for JOOMMF.
