### ISSUE TITLE
Skyrmion_DMI: Value Error: The t crystal class is not supported on win32 platform.

### ISSUE THREAD

**Issue by Ponsudana** [joommf/help#35]
Hello,
 Got an error while running the skyrmion program.
![Skyrmion_td_error](https://user-images.githubusercontent.com/43433451/56845511-0f4a4780-68e0-11e9-855a-6ea4480f051a.png)
Value Error: The t crystal class is not supported on win32 platform.
Help to resolve this.
Thank you,

**Comment by marijanbeg** [comment]
Hi @Ponsudana, unfortunately T(O) and D2d are not part of the Windows OOMMF distribution. Therefore, we cannot support it on Windows though JOOMMF. They are supported on MacOS and Linux. Please let us know if you have any further questions.
