### ISSUE TITLE
discretisedfield/field.py wrong base in .write()

### ISSUE THREAD

**Issue by dima-scientist** [joommf/help#36]
There is a bug in the discretisedfield.write(). It assigns base in a ovf file to a wrong position (uses for x, y, and z the same value pmin[0]):

In the line 367 of field.py is written:
 "xbase: {}".format(self.mesh.pmin[0] +
                                     self.mesh.cell[0]/2),
                  "ybase: {}".format(self.mesh.pmin[0] +
                                     self.mesh.cell[1]/2),
                  "zbase: {}".format(self.mesh.pmin[0] +
                                     self.mesh.cell[2]/2),

How it should be:

"xbase: {}".format(self.mesh.pmin[0] +
                                     self.mesh.cell[0]/2),
                  "ybase: {}".format(self.mesh.pmin[1] +
                                     self.mesh.cell[1]/2),
                  "zbase: {}".format(self.mesh.pmin[2] +
                                     self.mesh.cell[2]/2),

**Comment by marijanbeg** [comment]
Hi @dima-scientist, 
Thank you a lot for pointing out this typo. This is now fixed on master in `discretisedfield`. Please use `discretisedfield` from master now, until we update pip and conda packages. If you need any help with that or have any further questions, please let us know.
