### ISSUE TITLE
Help: DMI "Kind" in Linux.

### ISSUE THREAD

**Issue by Ponsudana** [joommf/help#38]
Hi,
I have switched from windows to Linux for using DMI crystal class which are not supported in windows.
When I define DMI with kind in Ubuntu, it gives an error.
How can I include interfacial DMI using JOOMMF in Linux?

Thanks,

**Comment by marijanbeg** [comment]
Hi @Ponsudana, in the new version of oommfc, different crystal classes are defines as: `oc.DMI(D, crystalclass='Cnv')`. Instead of `Cnv`, you can use `T` or `D2d` for different types of DMI.

I hope this helps, please let me know if you need any further help (feel free to reopen this issue).

**Comment by Ponsudana** [comment]
Yes, Thanks for the help 
So, to include interfacial DMI is it enough to define DMI as oc.DMI(D, crystalclass='Cnv') and for bulk as oc.DMI(D)?

**Comment by marijanbeg** [comment]
Yes, interfacial: `oc.DMI(D, crystalclass=Cnv)` and bulk: `oc.DMI(D, crystalclass=T)`.

**Comment by Ponsudana** [comment]
@marijanbeg Thank you.
