### ISSUE TITLE
Help: Initial value as *OMF file

### ISSUE THREAD

**Issue by Ponsudana** [joommf/help#39]
Hello,

I would like to include an OMF file as an initial value in a racetrack. How can I actually do it?

I have generated a skyrmion in a nanodisk which is saved as an OMF file.
Now, I wish to study the dynamics of the skyrmion in a racetrack.
How can I include the OMF file in a new mesh as a racetrack?

Thanks,

**Comment by marijanbeg** [comment]
Hi @Ponsudana, you can read the OMF file using the `read` function from `discretisedfield`. This is going to give you a `Field` object. After that, you pass that field to the `system`.

Does this resolve your issue? Please let us know if you need any further information.
