### ISSUE TITLE
Default evolver for the time driver

### ISSUE THREAD

**Issue by lleom582** [joommf/help#4]
hi
In the standard OOMMF distribution there are three evolvers for the time driver, to be selected: Oxs EulerEvolve, Oxs RungeKuttaEvolve, and Oxs SpinXferEvolve.

In Ubermag, which is the default used evolver if not specified when calling the time driver?

thank you in advance

**Comment by marijanbeg** [comment]
Hi @lleom582, thank you for your question. The default evolver is RungeKutta. Do you know how to change the evolver if necessary?

Please note that joommf was renamed to ubermag, so please raise all future issues in https://github.com/ubermag/help.

I will close this issue, but if there is anything else you want me to address, please raise an issue in https://github.com/ubermag/help.

Many thanks!
