### ISSUE TITLE
Determination of Current Density Value

### ISSUE THREAD

**Issue by Ponsudana** [joommf/help#41]
Hello,
How can I determine the value of current density while defining STT?

ux = 400 # velocity in x direction (m/s)
beta = 0.5 # non-adiabatic STT parameter
system.dynamics += oc.STT(u=(ux, 0, 0), beta=beta)

For the given value of velocity along x direction, it denoted the velocity of spin polarized electrons, polarized along x direction from the pinned layer (Polarizer). From this how can I get the value of current density?

I have made a small calculation using the formula, J=q . vd 
J- Current density
q- quantization of charge (q=ne)
vd- drift velocity
If so, how can I fix the value of "n"?

Thanks,

**Comment by marijanbeg** [comment]
Hi @Ponsudana, please refer to the OOMMF documentation for this specific extension: https://sites.google.com/site/spindgist/research/research-area/sst-extension

**Comment by Ponsudana** [comment]
Thank you @marijanbeg

**Comment by marijanbeg** [comment]
You can also maybe refer to standard problem 5 specification and a related paper at: https://www.ctcms.nist.gov/~rdm/mumag.org.html
