### ISSUE TITLE
dynamics representation

### ISSUE THREAD

**Issue by lleom582** [joommf/help#5]
hi
Is it possible to represent a system magnetization's dynamics in time instead of eg a dt.plot, like a video, in Ubermag?

thanks

**Comment by marijanbeg** [comment]
Hi @lleom582, please note that the repository we monitor for providing Ubermag support I: https://github.com/ubermag/help.

`micromagneticdata` is a package which provides this functionality. Please have a look at our workshop repository for examples: https://github.com/ubermag/workshop
