### ISSUE TITLE
Computing stray field

### ISSUE THREAD

**Issue by EduardoSBastos** [joommf/help#5]
Hello Jupyter team,

I would like to know, is the program capable of calculating and demonstrating stray/dipole fields? In case it can, could you provide a small example code on how to implement it?

Thanks in advance!

**Comment by mb1a15** [comment]
Hi,
You can ask for a demagnetisation (stray) field by typing:
```
stray_field = system.hamiltonian.demag.effective_field()
```
Now, in `stray_field` you have a `Field` object with which you can do all operations you do with magnetisation field (`system.m`), like plotting it.

You can find more details at http://oommfc.readthedocs.io/en/latest/ipynb/derived_fields.html. In this tutorial, we do not show demagnetisation field explicitly, but some basic concepts are included. I will make a small tutorial on computing stray fields and will let you know.

**Comment by marijanbeg** [comment]
I will consider that this has been answered in issue #24.

Please let us know if you have any further questions and feel free to reopen this issue if I did not answer your question.
