### ISSUE TITLE
Demagnetisation field for different geometries

### ISSUE THREAD

**Issue by EduardoSBastos** [joommf/help#6]
Hello Jupyter team,

Is there a way the program takes into consideration demagnetizing field of a certain geometry when calculating a magnetized material?

Thanks in advance.

**Comment by mb1a15** [comment]
Hi Eduardo,
Whenever the demagnetisation energy is included in the Hamiltonian (`system.hamiltonian = Demag() + ...`), demagnetisation field is computed for any geometry you defined. Therefore, you should not worry about different demagnetising fields for different geometries. I am not sure if that answers your question. Let us know if not.
