### ISSUE TITLE
Standard problem 3 with different answers

### ISSUE THREAD

**Issue by okmike** [joommf/help#6]
Hi, I have a problem with one variable in standard problem 3 , the discretisation in one dimension N  which is defined in the function minimise_system_energy. The tutorial defines the N = 16 and if I change N to 20 or 25, the final result will be very different from the one in the tutorial. I am new to the ubermag but should not the larger N (smaller cellsize for mesh) leads to more accurate results? Thank you for replying. 
![Result](https://user-images.githubusercontent.com/37909931/74607351-4742a580-5113-11ea-9c44-e8a74edbed5b.png)

**Comment by marijanbeg** [comment]
This support repository is now abandoned. Please open any issues in a new one: https://github.com/ubermag/help
