### ISSUE TITLE
same code different results...

### ISSUE THREAD

**Issue by abiague** [joommf/help#8]
I installed joommf in my computer and started running some tests by using two files from the tutorials provided in the joommf documentation. Tutorial 3 runs well and I get the same results as shown in the documentation. However, when I run Tutorial 12, the results look quite different. I do not get any warning or error message, the code runs without issues but the results differs from what is shown in the documentation.

Do you know what could be the source of such discrepancies?

Thanks,
Alex

**Comment by marijanbeg** [comment]
Hi Alex, thank you for your question. I cannot reproduce the problem you are reporting. Can you please attach the notebook or the resulting image you get?

**Comment by marijanbeg** [comment]
I am going to assume this issue is now resolved.

Please request any further support in our dedicated Ubermag help repository: https://github.com/ubermag/help
